### ISSUE TITLE
Simulación y Modelos 

### ISSUE THREAD

**Issue by Al3x28** [ejdecena/ejdecena.github.io#1]
Buenos días, Profesor Decena es Alejandro Girardi portador de la C.I:27.525.819. Soy estudiante de la materia simulación y modelos. Le escribo por si me puede informar, cual es la metodología a seguir este semestre?.

Muchas gracias por su atención, disculpe las molestias.

**Comment by ejdecena** [comment]
Hola, escríbeme a mi número celular 04248677041
